# (Des)carga de base de datos

## Instalación y carga de la librería del repositorio UCI ML

Instalar la librería del repositorio utilizando pip.

In [ ]:
pip install ucimlrepo

Verificar que la librería del repositorio se encuentra correctamente instalada.

In [ ]:
pip list | grep uci

Cargar la librería en la sesión actual de python.

In [1]:
from ucimlrepo import fetch_ucirepo

## Carga de la base de datos de cirrosis

Según la documentación del repositorio, nuestra base de datos de interés (cirrosis) se encuentra indexada con el id 878.

In [2]:
cirrhosis_patient_survival_prediction = fetch_ucirepo(id=878)

Ver cómo viene la información

In [ ]:
cirrhosis_patient_survival_prediction

Estructurar la información en un data frame

In [ ]:
X = cirrhosis_patient_survival_prediction.data.features
y = cirrhosis_patient_survival_prediction.data.targets
cirrosis = pd.concat([X,y], axis=1)

Ver las primeras observaciones

In [ ]:
cirrosis.head(10)

## En caso que fracasemos con la librería uci

Cargar librerías auxiliares

In [3]:
# Importar clase Path para utilizar rutas en directorios
from pathlib import Path
# Importar pandas para cargar base como dataframe
import pandas as pd

Ruta de trabajo actual para movernos entre directorios y poder leer la base correctamente.

In [4]:
BASE_DIR = Path().resolve().parent

Ver cual es el directorio al que apunta BASE_DIR

In [ ]:
BASE_DIR

Ruta de del directorio donde se encuentra el archivo de cirrosis

In [5]:
DATA_DIR = BASE_DIR / 'data' / 'cirrosis'
DATA_DIR

PosixPath('/Users/davidmoreno/Desktop/Diplomado 2025/DMEMCDM1/data/cirrosis')

Leer el archivo csv que se encuentra en el directorio de cirrosis utilizando pandas para estructurarlo en un data frame.

In [ ]:
cirrosis2 = pd.read_csv(DATA_DIR / 'cirrhosis.csv')

Ver las primeros renglones del data frame.

In [ ]:
cirrosis2.head(10)

## Sanity check

Verificar que tienen la misma dimensión

In [ ]:
cirrosis.shape

In [ ]:
cirrosis2.shape

Observamos que en cirrosis2 existen un par de columnas que no se encontraban en cirrosis:

In [ ]:
set(cirrosis2.columns).symmetric_difference(set(cirrosis.columns))

La columna 'ID' sirve de identificador por lo cual no representa ninguna diferencia significativa que pudiera afectar el análisis de nuestros datos. ¿Pero que pasa con 'N_Days'?

**Revisando la documentación** encontramos que dicha variable representaba el tiempo transcurrido desde que se registraban al estudio a que pasaba uno de los siguientes escenarios:
1. Muerte (D)
2. Trasplante (CL)
3. Fin del estudio (C)

Cómo nosotros no estamos haciendo el análisis de supervivencia y tomamos los datos con fines meramente de estudio, vamos a considerar N_Days también como variable explicativa.

## "Arreglo" de las bases

Primero voy a buscar como agregar la columna N_Days a mi base cirrosis. Explorando el objeto cirrhosis_patient_survival_prediction vemos que en data había un original que es idéntica a la tabla generada con cirrosis2.

In [6]:
cirrosis = cirrhosis_patient_survival_prediction.data.original
cirrosis.head(10)

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1,400,D,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261,2.60,156,1718.0,137.95,172,190,12.2,4.0
1,2,4500,C,D-penicillamine,20617,F,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6,3.0
2,3,1012,D,D-penicillamine,25594,M,N,N,N,S,1.4,176,3.48,210,516.0,96.10,55,151,12.0,4.0
3,4,1925,D,D-penicillamine,19994,F,N,Y,Y,S,1.8,244,2.54,64,6121.8,60.63,92,183,10.3,4.0
4,5,1504,CL,Placebo,13918,F,N,Y,Y,N,3.4,279,3.53,143,671.0,113.15,72,136,10.9,3.0
5,6,2503,D,Placebo,24201,F,N,Y,N,N,0.8,248,3.98,50,944.0,93.00,63,NaNN,11.0,3.0
6,7,1832,C,Placebo,20284,F,N,Y,N,N,1.0,322,4.09,52,824.0,60.45,213,204,9.7,3.0
7,8,2466,D,Placebo,19379,F,N,N,N,N,0.3,280,4.00,52,4651.2,28.38,189,373,11.0,3.0
8,9,2400,D,D-penicillamine,15526,F,N,N,Y,N,3.2,562,3.08,79,2276.0,144.15,88,251,11.0,2.0
9,10,51,D,Placebo,25772,F,Y,N,Y,Y,12.6,200,2.74,140,918.0,147.25,143,302,11.5,4.0

In [ ]:
all(cirrosis == cirrosis2)

De esta manera, podemos quedarnos solo con cirrosis, "descartando" la columna 'ID', y eliminar el objeto cirrosis2.

OJO: Dependiendo de la base que pudieron descargar, a esa le "descartan" la columna 'ID' y la otra no existía entonces no la borran.

In [7]:
cirrosis.set_index('ID', inplace=True)
cirrosis.head(2)

,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
ID,,,,,,,,,,,,,,,,,,,
1,400,D,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261,2.60,156,1718.0,137.95,172,190,12.2,4.0
2,4500,C,D-penicillamine,20617,F,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6,3.0

In [ ]:
del cirrosis2

Reordenaremos las columnas para tener la variable de interés (Status) al final.

In [8]:
cirrosis = cirrosis[[x for x in cirrosis.columns if x != 'Status'] + ['Status']]
cirrosis.head()

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
ID,,,,,,,,,,,,,,,,,,,
1,400,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261,2.60,156,1718.0,137.95,172,190,12.2,4.0,D
2,4500,D-penicillamine,20617,F,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6,3.0,C
3,1012,D-penicillamine,25594,M,N,N,N,S,1.4,176,3.48,210,516.0,96.10,55,151,12.0,4.0,D
4,1925,D-penicillamine,19994,F,N,Y,Y,S,1.8,244,2.54,64,6121.8,60.63,92,183,10.3,4.0,D
5,1504,Placebo,13918,F,N,Y,Y,N,3.4,279,3.53,143,671.0,113.15,72,136,10.9,3.0,CL

# Filtrado, ordenamiento, mezclas y agregación

## Filtrado de filas de acuerdo a condiciones lógicas

En ocasiones nos interesan ciertas observaciones por lo que necesitamos sera capaces de extraerlas. Veamos las distintas etapas que existen para luego filtrar las observaciones correspondientes con la etapa inicial de la enfermedad.

In [9]:
cirrosis.Stage.value_counts()

Stage
3.0    155
4.0    144
2.0     92
1.0     21
Name: count, dtype: int64

In [10]:
cirrosis_etapa_1 = cirrosis[cirrosis['Stage'] < 2]
cirrosis_etapa_1.head(5)

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
ID,,,,,,,,,,,,,,,,,,,
52,2386,D-penicillamine,18460,M,N,N,N,N,6.0,614,3.70,158,5084.4,206.40,93,362,10.6,1.0,D
58,4459,D-penicillamine,16279,M,N,N,N,N,0.7,242,4.08,73,5890.0,56.76,118,NaNN,10.6,1.0,C
61,4256,Placebo,16034,M,N,N,N,N,0.6,216,3.94,28,601.0,60.45,188,211,13.0,1.0,C
65,3992,D-penicillamine,14684,F,N,N,N,N,1.2,256,3.60,74,724.0,141.05,108,430,10.0,1.0,C
73,4190,Placebo,14060,F,N,N,N,N,0.7,132,3.60,17,423.0,49.60,56,265,11.0,1.0,C

In [12]:
cirrosis_etapa_1.Stage.value_counts()

Stage
1.0    21
Name: count, dtype: int64

OJO: Cuidado con el tipo de dato que tienen porque en ocasiones al no tomarlo en consideración las operaciones y los filtros pueden no comportarse de manera adecuada.

In [17]:
cirrosis[cirrosis['Stage'] == '1.0']

Empty DataFrame
Columns: [N_Days, Drug, Age, Sex, Ascites, Hepatomegaly, Spiders, Edema, Bilirubin, Cholesterol, Albumin, Copper, Alk_Phos, SGOT, Tryglicerides, Platelets, Prothrombin, Stage, Status]
Index: []

En ocasiones se pueden necesitar filtros que dependan de más de una variables; por ejemplo, menores de edad en etapa 1 de género F. Hay que tener cuidado pues la edad esta en días.

In [18]:
stage_mask = (cirrosis['Stage'] < 2)
stage_mask

ID
1      False
2      False
3      False
4      False
5      False
       ...
414    False
415    False
416    False
417    False
418    False
Name: Stage, Length: 418, dtype: bool

Para verificar que funciona bien la máscara, pueden sumar los boleanos y deberían ser 21

In [19]:
stage_mask.sum()

np.int64(21)

In [21]:
age_mask = (cirrosis['Age'] / 365 < 18)
sex_mask = (cirrosis['Sex'] == 'F')

Filtro las observaciones que cumplan con todos los requisitos.

In [22]:
cirrosis_F_menores_edad = cirrosis[stage_mask & age_mask & sex_mask]

Equivalentemente podrían escribirlo como sigue

In [ ]:
cirrosis[(cirrosis['Stage'] < 2) & (cirrosis['Age'] / 365 < 18) & (cirrosis['Sex'] == 'F')]

Empty DataFrame
Columns: [N_Days, Drug, Age, Sex, Ascites, Hepatomegaly, Spiders, Edema, Bilirubin, Cholesterol, Albumin, Copper, Alk_Phos, SGOT, Tryglicerides, Platelets, Prothrombin, Stage, Status]
Index: []

In [27]:
cirrosis_F_menores_edad

Empty DataFrame
Columns: [N_Days, Drug, Age, Sex, Ascites, Hepatomegaly, Spiders, Edema, Bilirubin, Cholesterol, Albumin, Copper, Alk_Phos, SGOT, Tryglicerides, Platelets, Prothrombin, Stage, Status]
Index: []

Observamos que en el estudio no hay menores de edad

In [28]:
(cirrosis['Age'] / 365 < 18).sum()

np.int64(0)

Nos enteramos que no es legal hacer estudios clínicos experimentales en niños (sin consentimiento de sus tutores legales y en casos no extremos) por lo cual nuestra base no tiene información de menores de edad.

Bueno... vamos a relajar un poco el supuesto y digamos que queremos menores de edad o mayores de 65 años.

In [29]:
age_mask_2 = age_mask | (cirrosis['Age'] / 365 > 65)
cirrosis_F_no_laboral = cirrosis[stage_mask & sex_mask & age_mask_2]

Equivalentemente...

In [30]:
cirrosis[(cirrosis['Stage'] < 2) & ((cirrosis['Age'] / 365 < 18) | (cirrosis['Age'] / 365 > 65)) & (cirrosis['Sex'] == 'F')]

Empty DataFrame
Columns: [N_Days, Drug, Age, Sex, Ascites, Hepatomegaly, Spiders, Edema, Bilirubin, Cholesterol, Albumin, Copper, Alk_Phos, SGOT, Tryglicerides, Platelets, Prothrombin, Stage, Status]
Index: []

In [32]:
cirrosis_F_no_laboral

Empty DataFrame
Columns: [N_Days, Drug, Age, Sex, Ascites, Hepatomegaly, Spiders, Edema, Bilirubin, Cholesterol, Albumin, Copper, Alk_Phos, SGOT, Tryglicerides, Platelets, Prothrombin, Stage, Status]
Index: []

Haciendo un análisis de la información vemos que el rango de edad en pacientes género 'F' que se encuentran en etapa 1 esta entre 28 y 62 años. Por lo cual hace sentido que no recuperemos información.

In [36]:
(cirrosis[stage_mask].Age /365).describe()

count    21.000000
mean     46.873190
std       9.552225
min      28.904110
25%      38.520548
50%      46.380822
75%      53.035616
max      62.564384
Name: Age, dtype: float64

In [37]:
(cirrosis[sex_mask].Age /365).describe()

count    374.000000
mean      50.191297
std       10.247664
min       26.295890
25%       42.407534
50%       50.227397
75%       57.038356
max       76.761644
Name: Age, dtype: float64

In [38]:
(cirrosis[age_mask_2].Age /365).describe()

count    40.000000
mean     69.141644
std       3.251015
min      65.043836
25%      67.046575
50%      68.278082
75%      70.242466
max      78.493151
Name: Age, dtype: float64

## Selección de variables (columnas)

In [39]:
cirrosis.head(2)

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
ID,,,,,,,,,,,,,,,,,,,
1,400,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261,2.60,156,1718.0,137.95,172,190,12.2,4.0,D
2,4500,D-penicillamine,20617,F,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6,3.0,C

In [40]:
cirrosis.columns

Index(['N_Days', 'Drug', 'Age', 'Sex', 'Ascites', 'Hepatomegaly', 'Spiders',
       'Edema', 'Bilirubin', 'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos',
       'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin', 'Stage', 'Status'],
      dtype='object')

Guardar nombres de distintas variables en listas dependiendo de su tipo o significado.

In [41]:
signos_clinicos = ['Ascites', 'Hepatomegaly', 'Spiders', 'Edema']
nivels_sangre = ['Bilirubin', 'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin']
variables_categoricas_nominales = ['Drug', 'Sex', 'Status']
variables_categoricas_ordinales = ['Stage']
variables_continuas = ['N_Days', 'Age']

Sanity check que no elimine variables...

In [42]:
len(signos_clinicos) + len(nivels_sangre) + len(variables_categoricas_nominales) + len(variables_categoricas_ordinales) + len(variables_continuas) == len(cirrosis.columns)

True

Qué pasa si de momento sólo nos interesan los signos clínicos.

In [45]:
cirrosis_signos_clínicos = cirrosis[signos_clinicos]
cirrosis_signos_clínicos.head()

   Ascites Hepatomegaly Spiders Edema
ID
1        Y            Y       Y     Y
2        N            Y       Y     N
3        N            N       N     S
4        N            Y       Y     S
5        N            Y       Y     N

Equivalentemente se podría hacer de la siguiente manera:

In [46]:
cirrosis[['Ascites', 'Hepatomegaly', 'Spiders', 'Edema']]

    Ascites Hepatomegaly Spiders Edema
ID
1         Y            Y       Y     Y
2         N            Y       Y     N
3         N            N       N     S
4         N            Y       Y     S
5         N            Y       Y     N
..      ...          ...     ...   ...
414     NaN          NaN     NaN     N
415     NaN          NaN     NaN     N
416     NaN          NaN     NaN     N
417     NaN          NaN     NaN     N
418     NaN          NaN     NaN     N

[418 rows x 4 columns]

De igual manera, podríamos querer las variables de signo clínico y de niveles en sangre.

In [48]:
cirrosis_variables_médicas = cirrosis[signos_clinicos + nivels_sangre]
cirrosis_variables_médicas.head()

,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin
ID,,,,,,,,,,,,,
1,Y,Y,Y,Y,14.5,261,2.60,156,1718.0,137.95,172,190,12.2
2,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6
3,N,N,N,S,1.4,176,3.48,210,516.0,96.10,55,151,12.0
4,N,Y,Y,S,1.8,244,2.54,64,6121.8,60.63,92,183,10.3
5,N,Y,Y,N,3.4,279,3.53,143,671.0,113.15,72,136,10.9

In [49]:
signos_clinicos + nivels_sangre

['Ascites',
 'Hepatomegaly',
 'Spiders',
 'Edema',
 'Bilirubin',
 'Cholesterol',
 'Albumin',
 'Copper',
 'Alk_Phos',
 'SGOT',
 'Tryglicerides',
 'Platelets',
 'Prothrombin']

Equivalentemente...

In [50]:
cirrosis[['Ascites', 'Hepatomegaly', 'Spiders', 'Edema', 'Bilirubin', 'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin']]

,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin
ID,,,,,,,,,,,,,
1,Y,Y,Y,Y,14.5,261,2.60,156,1718.0,137.95,172,190,12.2
2,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6
3,N,N,N,S,1.4,176,3.48,210,516.0,96.10,55,151,12.0
4,N,Y,Y,S,1.8,244,2.54,64,6121.8,60.63,92,183,10.3
5,N,Y,Y,N,3.4,279,3.53,143,671.0,113.15,72,136,10.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,NaN,NaN,NaN,N,1.2,NaN,2.96,NaN,NaN,NaN,NaN,174,10.9
415,NaN,NaN,NaN,N,0.9,NaN,3.83,NaN,NaN,NaN,NaN,180,11.2
416,NaN,NaN,NaN,N,1.6,NaN,3.42,NaN,NaN,NaN,NaN,143,9.9
417,NaN,NaN,NaN,N,0.8,NaN,3.75,NaN,NaN,NaN,NaN,269,10.4
418,NaN,NaN,NaN,N,0.7,NaN,3.29,NaN,NaN,NaN,NaN,350,10.6

Hack:

In [51]:
cirrosis[[
    'Ascites', 'Hepatomegaly', 'Spiders', 'Edema', 'Bilirubin',
    'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin'
]]

,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin
ID,,,,,,,,,,,,,
1,Y,Y,Y,Y,14.5,261,2.60,156,1718.0,137.95,172,190,12.2
2,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6
3,N,N,N,S,1.4,176,3.48,210,516.0,96.10,55,151,12.0
4,N,Y,Y,S,1.8,244,2.54,64,6121.8,60.63,92,183,10.3
5,N,Y,Y,N,3.4,279,3.53,143,671.0,113.15,72,136,10.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,NaN,NaN,NaN,N,1.2,NaN,2.96,NaN,NaN,NaN,NaN,174,10.9
415,NaN,NaN,NaN,N,0.9,NaN,3.83,NaN,NaN,NaN,NaN,180,11.2
416,NaN,NaN,NaN,N,1.6,NaN,3.42,NaN,NaN,NaN,NaN,143,9.9
417,NaN,NaN,NaN,N,0.8,NaN,3.75,NaN,NaN,NaN,NaN,269,10.4
418,NaN,NaN,NaN,N,0.7,NaN,3.29,NaN,NaN,NaN,NaN,350,10.6

## Ordenamiento

Tal vez quisieramos ordenar la información de acuerdo a la edad de los pacientes...

In [55]:
cirrosis_orden_edad_decreciente = cirrosis.sort_values(by='Age', ascending=False)
cirrosis_orden_edad_decreciente

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
ID,,,,,,,,,,,,,,,,,,,
253,1765,D-penicillamine,28650,M,Y,Y,Y,N,7.1,243,3.03,380,983.0,158.10,154,97,11.2,4.0,C
92,388,D-penicillamine,28018,F,Y,N,N,Y,1.4,206,3.13,36,1626.0,86.80,70,145,12.2,4.0,D
147,2995,D-penicillamine,27398,F,N,N,N,S,1.2,288,3.37,32,791.0,57.35,114,213,10.7,2.0,C
316,2071,NaN,27394,F,NaN,NaN,NaN,S,0.7,NaN,3.96,NaN,NaN,NaN,NaN,NaN,11.3,4.0,D
260,1656,Placebo,27220,M,N,Y,N,N,5.6,232,3.59,188,1120.0,98.00,128,248,10.9,4.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,1149,Placebo,11167,F,N,N,N,N,0.8,273,3.56,52,1282.0,130.00,59,344,10.5,2.0,C
173,2657,D-penicillamine,11058,F,N,Y,Y,N,3.0,236,3.42,76,1403.0,89.90,86,493,9.8,2.0,C
195,2330,D-penicillamine,10795,F,N,Y,N,N,3.7,347,3.90,76,2544.0,221.65,90,129,11.5,4.0,C
98,3823,D-penicillamine,10550,F,N,N,N,N,1.0,239,3.77,77,1877.0,97.65,101,312,10.2,1.0,C
270,1568,D-penicillamine,9598,F,N,Y,Y,N,1.0,448,3.74,102,1128.0,71.00,117,228,10.2,3.0,C

In [56]:
cirrosis_orden_edad_creciente = cirrosis.sort_values(by='Age', ascending=True)
cirrosis_orden_edad_creciente

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
ID,,,,,,,,,,,,,,,,,,,
270,1568,D-penicillamine,9598,F,N,Y,Y,N,1.0,448,3.74,102,1128.0,71.00,117,228,10.2,3.0,C
98,3823,D-penicillamine,10550,F,N,N,N,N,1.0,239,3.77,77,1877.0,97.65,101,312,10.2,1.0,C
195,2330,D-penicillamine,10795,F,N,Y,N,N,3.7,347,3.90,76,2544.0,221.65,90,129,11.5,4.0,C
173,2657,D-penicillamine,11058,F,N,Y,Y,N,3.0,236,3.42,76,1403.0,89.90,86,493,9.8,2.0,C
307,1149,Placebo,11167,F,N,N,N,N,0.8,273,3.56,52,1282.0,130.00,59,344,10.5,2.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,1656,Placebo,27220,M,N,Y,N,N,5.6,232,3.59,188,1120.0,98.00,128,248,10.9,4.0,C
316,2071,NaN,27394,F,NaN,NaN,NaN,S,0.7,NaN,3.96,NaN,NaN,NaN,NaN,NaN,11.3,4.0,D
147,2995,D-penicillamine,27398,F,N,N,N,S,1.2,288,3.37,32,791.0,57.35,114,213,10.7,2.0,C
92,388,D-penicillamine,28018,F,Y,N,N,Y,1.4,206,3.13,36,1626.0,86.80,70,145,12.2,4.0,D
253,1765,D-penicillamine,28650,M,Y,Y,Y,N,7.1,243,3.03,380,983.0,158.10,154,97,11.2,4.0,C

Y si me interesa ordenar de acuerdo a varias variables?

Por ejemplo, nos intersa ordenar por etapa y número de días desde diagnóstico a el suceso..

In [57]:
cirrosis_orden_etapa_creciente_dias_creciente = cirrosis.sort_values(by=['Stage', 'N_Days'])
cirrosis_orden_etapa_creciente_dias_creciente

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
ID,,,,,,,,,,,,,,,,,,,
371,489,NaN,18628,F,NaN,NaN,NaN,S,7.3,NaN,3.52,NaN,NaN,NaN,NaN,265,11.1,1.0,D
395,1329,NaN,13149,F,NaN,NaN,NaN,N,1.4,NaN,3.98,NaN,NaN,NaN,NaN,402,11.0,1.0,C
285,1401,D-penicillamine,16929,F,N,N,N,N,0.8,253,3.48,65,688.0,57.0,80,252,10.0,1.0,C
272,1525,D-penicillamine,14025,F,N,N,N,N,0.5,226,2.93,22,674.0,58.0,85,153,9.8,1.0,C
384,1639,NaN,21550,F,NaN,NaN,NaN,N,1.3,NaN,3.40,NaN,NaN,NaN,NaN,243,9.7,1.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,466,NaN,20454,F,NaN,NaN,NaN,N,7.1,NaN,3.51,NaN,NaN,NaN,NaN,721,11.8,NaN,D
322,2011,NaN,23376,F,NaN,NaN,NaN,N,1.1,NaN,3.69,NaN,NaN,NaN,NaN,139,10.5,NaN,D
337,2286,NaN,20454,F,NaN,NaN,NaN,N,1.8,NaN,3.64,NaN,NaN,NaN,NaN,141,10.0,NaN,D
317,3030,NaN,22646,F,NaN,NaN,NaN,N,0.8,NaN,2.48,NaN,NaN,NaN,NaN,273,10.0,NaN,C
313,4062,NaNN,21915,F,NaNN,NaNN,NaNN,N,0.7,NaN,3.65,NaN,NaN,NaN,NaN,378,11.0,NaN,C

Como verán no vemos todas las filas por lo que hay que modificar los parámetros de pandas

In [58]:
pd.set_option('display.max_rows', None)

In [59]:
cirrosis_orden_etapa_creciente_dias_creciente

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
ID,,,,,,,,,,,,,,,,,,,
371,489,NaN,18628,F,NaN,NaN,NaN,S,7.3,NaN,3.52,NaN,NaN,NaN,NaN,265,11.1,1.0,D
395,1329,NaN,13149,F,NaN,NaN,NaN,N,1.4,NaN,3.98,NaN,NaN,NaN,NaN,402,11.0,1.0,C
285,1401,D-penicillamine,16929,F,N,N,N,N,0.8,253,3.48,65,688.0,57.00,80,252,10.0,1.0,C
272,1525,D-penicillamine,14025,F,N,N,N,N,0.5,226,2.93,22,674.0,58.00,85,153,9.8,1.0,C
384,1639,NaN,21550,F,NaN,NaN,NaN,N,1.3,NaN,3.40,NaN,NaN,NaN,NaN,243,9.7,1.0,C
258,1702,D-penicillamine,18806,F,N,N,N,N,1.1,414,3.44,80,1003.0,99.00,55,271,9.6,1.0,C
218,2170,D-penicillamine,12636,F,N,N,N,N,0.5,NaNN,3.89,29,897.0,66.65,NaNN,423,10.1,1.0,C
206,2255,D-penicillamine,22642,F,N,N,N,N,0.6,213,4.07,12,5300.0,57.35,68,240,11.0,1.0,C
52,2386,D-penicillamine,18460,M,N,N,N,N,6.0,614,3.70,158,5084.4,206.40,93,362,10.6,1.0,D
359,2534,NaN,16802,F,NaN,NaN,NaN,N,0.8,NaN,2.89,NaN,NaN,NaN,NaN,419,NaN,1.0,C
174,2644,D-penicillamine,20296,F,N,N,N,N,0.5,NaNN,3.85,63,663.0,79.05,NaNN,311,9.7,1.0,C
352,2716,NaN,19358,F,NaN,NaN,NaN,N,0.6,NaN,4.19,NaN,NaN,NaN,NaN,330,9.9,1.0,C
153,2863,D-penicillamine,18118,F,N,N,N,N,0.5,217,3.85,68,453.0,54.25,68,270,11.1,1.0,C
150,2891,Placebo,12779,F,N,N,Y,N,1.0,NaNN,3.63,57,1536.0,134.85,NaNN,233,10.0,1.0,C
102,3099,D-penicillamine,20662,F,N,N,N,N,0.9,248,3.97,172,646.0,62.00,84,128,10.1,1.0,C
107,3388,Placebo,22836,F,N,N,N,N,0.6,212,4.03,10,648.0,71.30,77,316,17.1,1.0,C
98,3823,D-penicillamine,10550,F,N,N,N,N,1.0,239,3.77,77,1877.0,97.65,101,312,10.2,1.0,C
65,3992,D-penicillamine,14684,F,N,N,N,N,1.2,256,3.60,74,724.0,141.05,108,430,10.0,1.0,C
73,4190,Placebo,14060,F,N,N,N,N,0.7,132,3.60,17,423.0,49.60,56,265,11.0,1.0,C
61,4256,Placebo,16034,M,N,N,N,N,0.6,216,3.94,28,601.0,60.45,188,211,13.0,1.0,C
58,4459,D-penicillamine,16279,M,N,N,N,N,0.7,242,4.08,73,5890.0,56.76,118,NaNN,10.6,1.0,C
95,130,Placebo,16944,F,Y,Y,Y,Y,17.4,NaNN,2.64,182,559.0,119.35,NaNN,401,11.7,2.0,D
343,625,NaN,17532,F,NaN,NaN,NaN,N,11.1,NaN,2.84,NaN,NaN,NaN,NaN,NaN,12.2,2.0,D
312,788,Placebo,12109,F,N,N,Y,N,6.4,576,3.79,186,2115.0,136.00,149,200,10.8,2.0,C
338,791,NaN,17167,F,NaN,NaN,NaN,N,16.0,NaN,3.42,NaN,NaN,NaN,NaN,475,13.8,2.0,D
289,799,D-penicillamine,24681,M,N,Y,N,S,4.0,416,3.99,177,960.0,86.00,242,269,9.8,2.0,D
311,839,D-penicillamine,13879,F,N,N,N,N,2.0,247,3.16,69,1050.0,117.00,88,335,10.5,2.0,C
156,853,Placebo,21699,F,N,Y,N,N,25.5,358,3.52,219,2468.0,201.50,205,151,11.5,2.0,D
310,939,D-penicillamine,22767,F,N,N,N,N,1.7,434,3.35,39,1713.0,171.00,100,234,10.2,2.0,C
354,990,NaN,21550,F,NaN,NaN,NaN,N,1.3,NaN,3.12,NaN,NaN,NaN,NaN,125,9.6,2.0,D
309,994,Placebo,21294,F,N,N,N,N,0.4,260,2.75,41,1166.0,70.00,82,231,10.8,2.0,C
227,999,D-penicillamine,21532,M,N,N,N,N,2.3,316,3.35,172,1601.0,179.80,63,394,9.7,2.0,D
288,1067,Placebo,17874,F,N,Y,N,S,8.7,310,3.89,107,637.0,117.00,242,298,9.6,2.0,CL
307,1149,Placebo,11167,F,N,N,N,N,0.8,273,3.56,52,1282.0,130.00,59,344,10.5,2.0,C
308,1153,D-penicillamine,22347,F,N,Y,N,N,0.4,246,3.58,24,797.0,91.00,113,288,10.4,2.0,C
378,1168,NaN,21915,F,NaN,NaN,NaN,S,1.8,NaN,3.62,NaN,NaN,NaN,NaN,225,9.9,2.0,D
306,1216,Placebo,20597,F,N,Y,N,N,0.6,239,3.45,31,1072.0,55.00,64,227,10.7,2.0,C
400,1223,NaN,16071,F,NaN,NaN,NaN,N,0.5,NaN,3.34,NaN,NaN,NaN,NaN,258,10.6,2.0,C
220,1235,D-penicillamine,23241,F,N,N,Y,N,3.8,426,3.22,96,2716.0,210.80,113,228,10.6,2.0,D
399,1260,NaN,15341,F,NaN,NaN,NaN,N,8.1,NaN,2.82,NaN,NaN,NaN,NaN,193,10.4,2.0,C
302,1271,D-penicillamine,13806,F,N,N,N,N,0.7,335,3.95,43,657.0,52.00,104,268,10.6,2.0,C
396,1343,NaN,18263,F,NaN,NaN,NaN,N,1.6,NaN,3.48,NaN,NaN,NaN,NaN,277,10.2,2.0,C
269,1363,Placebo,16467,F,N,N,N,N,3.6,374,3.50,143,1428.0,188.00,44,151,10.1,2.0,C
279,1433,Placebo,20510,F,N,N,N,N,0.5,198,3.77,38,911.0,57.00,56,280,9.8,2.0,C
391,1443,NaN,14975,F,NaN,NaN,NaN,N,1.2,NaN,2.80,NaN,NaN,NaN,NaN,120,11.0,2.0,C
251,1457,D-penicillamine,20810,F,N,N,N,N,0.5,227,3.61,40,676.0,83.00,120,249,9.9,2.0,C
276,1481,D-penicillamine,18302,F,N,N,N,N,1.0,219,3.85,67,640.0,145.00,108,95,10.7,2.0,C
257,1614,D-penicillamine,21281,F,N,N,N,N,0.5,280,4.23,36,377.0,56.00,146,227,10.6,2.0,C
318,1680,NaN,15706,F,NaN,NaN,NaN,N,0.7,NaN,3.68,NaN,NaN,NaN,NaN,306,9.5,2.0,C
89,1741,D-penicillamine,19155,F,N,Y,N,N,2.0,408,3.65,50,1083.0,110.05,98,200,11.4,2.0,D
330,1746,NaN,19724,M,NaN,NaN,NaN,N,3.5,NaN,3.63,NaN,NaN,NaN,NaN,325,10.3,2.0,D
234,1776,Placebo,12557,F,N,N,N,N,0.9,578,3.35,78,976.0,116.25,177,322,11.2,2.0,C
56,1847,Placebo,12279,F,N,Y,Y,N,1.1,498,3.80,88,13862.4,95.46,319,365,10.6,2.0,D
238,1874,Placebo,24257,F,N,N,N,S,0.6,280,3.35,NaNN,1093.0,128.65,81,295,9.8,2.0,C
225,2022,D-penicillamine,14161,F,N,N,N,N,0.7,274,3.66,108,1065.0,88.35,135,251,10.1,2.0,C
373,2103,NaN,22646,F,NaN,NaN,NaN,N,0.7,NaN,3.29,NaN,NaN,NaN,NaN,190,9.8,2.0,C
328,2111,NaN,19724,F,NaN,NaN,NaN,N,1.0,NaN,3.60,NaN,NaN,NaN,NaN,NaN,12.1,2.0,D
372,2149,NaN,13514,F,NaN,NaN,NaN,N,0.6,NaN,3.55,NaN,NaN,NaN,NaN,248,10.3,2.0,C
209,2216,Placebo,19221,F,N,Y,Y,N,0.7,252,4.01,11,1210.0,72.85,58,309,9.5,2.0,C
203,2221,Placebo,13535,F,N,Y,N,N,0.5,149,4.04,227,598.0,52.70,57,166,9.9,2.0,C
210,2224,Placebo,18176,M,N,Y,N,N,0.9,346,3.37,81,1098.0,122.45,90,298,10.0,2.0,C
183,2241,Placebo,14705,F,N,N,N,N,0.5,201,3.73,44,1345.0,54.25,145,445,10.1,2.0,CL
362,2267,NaN,17897,F,NaN,NaN,NaN,N,18.0,NaN,3.04,NaN,NaN,NaN,NaN,432,9.7,2.0,CL
202,2272,D-penicillamine,22514,F,N,N,N,N,0.5,223,3.80,15,1044.0,80.60,89,514,10.0,2.0,C
198,2357,Placebo,13075,F,N,N,Y,N,0.7,286,2.90,38,1692.0,141.05,90,381,9.6,2.0,C
197,2365,D-penicillamine,16300,F,N,N,N,N,0.6,266,3.97,25,1164.0,102.30,102,201,10.1,2.0,C
9,2400,D-penicillamine,15526,F,N,N,Y,N,3.2,562,3.08,79,2276.0,144.15,88,251,11.0,2.0,D
142,2419,Placebo,20354,F,N,Y,N,N,1.0,364,3.48,20,720.0,134.85,88,283,9.9,2.0,D
194,2449,D-penicillamine,16216,F,N,N,N,N,1.5,293,4.30,50,975.0,125.55,56,336,9.1,2.0,C
158,2475,D-penicillamine,13329,F,N,N,N,N,3.4,450,3.37,32,1408.0,116.25,118,313,11.2,2.0,CL
190,2504,D-penicillamine,19916,F,N,N,Y,N,2.3,NaNN,3.93,24,1828.0,133.30,NaNN,327,10.2,2.0,C
182,2555,D-penicillamine,20799,F,N,Y,N,N,0.6,NaNN,3.69,161,674.0,26.35,NaNN,539,9.9,2.0,C
108,2583,D-penicillamine,18393,F,N,N,N,N,0.4,127,3.50,14,1062.0,49.60,84,334,10.3,2.0,D
177,2609,Placebo,20254,F,N,N,N,N,0.9,258,4.01,49,559.0,43.40,133,277,10.4,2.0,C
173,2657,D-penicillamine,11058,F,N,Y,Y,N,3.0,236,3.42,76,1403.0,89.90,86,493,9.8,2.0,C
90,2689,D-penicillamine,12227,M,N,N,N,N,1.6,660,4.22,94,1857.0,151.90,155,337,11.0,2.0,D
168,2713,Placebo,17442,F,N,Y,N,N,0.4,257,3.80,44,842.0,97.65,110,NaNN,9.2,2.0,C
166,2721,Placebo,15105,F,N,Y,N,N,5.7,1480,3.26,84,1960.0,457.25,108,213,9.5,2.0,C
161,2797,Placebo,15612,F,N,N,N,N,2.3,502,3.56,4,964.0,120.90,180,269,9.6,2.0,C
347,2812,NaN,18628,F,NaN,NaN,NaN,N,3.4,NaN,3.92,NaN,NaN,NaN,NaN,NaN,9.3,2.0,D
348,2834,NaN,18993,M,NaN,NaN,NaN,N,0.9,NaN,3.14,NaN,NaN,NaN,NaN,191,12.3,2.0,C
157,2835,Placebo,17809,F,N,N,N,N,0.6,286,3.42,34,1868.0,77.50,206,487,10.0,2.0,C
349,2855,NaN,19724,F,NaN,NaN,NaN,N,1.4,NaN,3.82,NaN,NaN,NaN,NaN,249,10.3,2.0,C
151,2870,D-penicillamine,20104,F,N,N,N,N,0.9,460,3.03,57,721.0,85.25,174,301,9.4,2.0,C
137,2990,D-penicillamine,22960,F,N,N,N,N,1.1,399,3.60,79,3472.0,155.00,152,344,10.1,2.0,C
147,2995,D-penicillamine,27398,F,N,N,N,S,1.2,288,3.37,32,791.0,57.35,114,213,10.7,2.0,C
345,3021,NaN,17532,F,NaN,NaN,NaN,N,0.5,NaN,3.76,NaN,NaN,NaN,NaN,388,10.1,2.0,CL
141,3050,D-penicillamine,17180,F,N,N,N,N,0.9,346,3.77,59,794.0,125.55,56,336,10.6,2.0,C
104,3086,D-penicillamine,15712,F,N,N,N,N,1.1,303,3.64,20,2108.0,128.65,53,349,11.1,2.0,D
136,3098,D-penicillamine,20440,F,N,N,N,N,0.8,263,3.35,27,1636.0,116.25,69,206,9.8,2.0,C
134,3149,Placebo,15463,F,N,N,N,N,0.7,578,3.67,35,1353.0,127.10,105,427,10.7,2.0,C
135,3150,D-penicillamine,15694,F,N,N,N,N,0.4,263,3.57,123,836.0,74.40,121,445,11.0,2.0,C
106,3222,D-penicillamine,25023,F,Y,Y,N,N,2.1,NaNN,3.90,50,1087.0,103.85,NaNN,137,10.6,2.0,D
127,3255,Placebo,16109,F,N,N,N,N,0.5,268,4.08,9,1174.0,86.80,95,453,10.0,2.0,C
70,3458,D-penicillamine,20600,F,N,N,N,N,0.6,NaNN,4.64,20,666.0,54.25,NaNN,265,10.6,2.0,C
324,3468,NaN,23011,F,NaN,NaN,NaN,N,0.6,NaN,3.94,NaN,NaN,NaN,NaN,234,11.5,2.0,C
339,3492,NaN,21915,F,NaN,NaN,NaN,N,0.6,NaN,4.38,NaN,NaN,NaN,NaN,269,10.6,2.0,C
340,3495,NaN,19358,F,NaN,NaN,NaN,N,5.4,NaN,4.19,NaN,NaN,NaN,NaN,141,11.2,2.0,C
323,3523,NaN,14610,F,NaN,NaN,NaN,N,0.6,NaN,4.04,NaN,NaN,NaN,NaN,130,11.2,2.0,C
335,3527,NaN,20089,F,NaN,NaN,NaN,N,0.6,NaN,4.15,NaN,NaN,NaN,NaN,280,10.1,2.0,C
36,3611,Placebo,20604,F,N,N,N,N,0.3,172,3.39,18,558.0,71.30,96,311,10.6,2.0,C
99,3820,Placebo,17703,M,N,N,N,N,1.8,460,3.35,148,1472.0,108.50,118,172,10.2,2.0,C
31,3839,Placebo,15177,F,N,Y,N,N,4.7,296,3.44,114,9933.2,206.40,101,195,10.3,2.0,D
51,3853,Placebo,19025,F,N,N,N,N,0.8,276,3.60,54,4332.0,99.33,143,273,10.6,2.0,D
93,3913,D-penicillamine,13344,F,N,N,N,N,1.3,353,3.67,73,2039.0,232.50,68,380,11.1,2.0,C
34,3933,D-penicillamine,19015,F,N,N,N,N,0.8,364,3.70,37,1840.0,170.50,64,273,10.5,2.0,C
45,4025,Placebo,15265,F,N,N,N,N,0.6,NaNN,3.93,19,1826.0,71.30,NaNN,474,10.9,2.0,C
24,4079,D-penicillamine,16261,M,N,Y,N,N,2.1,456,4.00,124,5719.0,221.88,230,70,9.9,2.0,D
25,4127,Placebo,16463,F,N,N,N,N,0.7,298,4.10,40,661.0,106.95,66,324,11.3,2.0,C
327,4214,NaN,17897,F,NaN,NaN,NaN,N,1.2,NaN,3.99,NaN,NaN,NaN,NaN,NaN,11.2,2.0,C
29,4509,Placebo,23331,F,N,N,N,N,0.7,370,3.78,24,5833.0,73.53,86,390,10.6,2.0,C
43,4556,D-penicillamine,17850,F,N,N,N,N,1.1,361,3.64,36,5430.2,67.08,89,203,10.6,2.0,C
325,4795,NaN,12419,F,NaN,NaN,NaN,N,1.8,NaN,3.24,NaN,NaN,NaN,NaN,NaN,18.0,2.0,C
154,140,D-penicillamine,25340,M,N,N,Y,Y,2.4,168,2.56,225,1056.0,120.90,75,108,14.1,3.0,D
87,198,D-penicillamine,13616,F,N,N,N,N,1.1,345,4.40,75,1860.0,218.55,72,447,10.7,3.0,D
366,249,NaN,22280,F,NaN,NaN,NaN,N,1.3,NaN,3.01,NaN,NaN,NaN,NaN,223,10.7,3.0,D
77,326,Placebo,18199,F,N,Y,Y,S,6.6,244,3.41,199,1819.0,170.50,91,132,12.1,3.0,D
119,515,D-penicillamine,19817,F,N,N,Y,N,0.6,636,3.83,129,944.0,97.65,114,306,9.5,3.0,D
222,597,Placebo,16898,F,N,Y,N,N,4.5,372,3.38,227,2310.0,167.40,135,240,12.4,3.0,D
97,611,Placebo,26259,M,N,Y,N,S,2.0,420,3.26,62,3196.0,77.50,91,344,11.4,3.0,D
350,662,NaN,17532,F,NaN,NaN,NaN,N,2.1,NaN,4.10,NaN,NaN,NaN,NaN,200,9.0,3.0,D
414,681,NaN,24472,F,NaN,NaN,NaN,N,1.2,NaN,2.96,NaN,NaN,NaN,NaN,174,10.9,3.0,D
417,691,NaN,21185,F,NaN,NaN,NaN,N,0.8,NaN,3.75,NaN,NaN,NaN,NaN,269,10.4,3.0,C
247,732,D-penicillamine,15056,F,N,Y,N,N,6.1,1712,2.83,89,3681.0,158.10,139,297,10.0,3.0,CL
187,733,Placebo,13073,F,N,Y,N,N,14.0,808,3.43,251,2870.0,153.45,137,268,11.5,3.0,D
254,737,D-penicillamine,14558,F,N,Y,Y,N,3.1,227,3.75,121,1136.0,110.00,91,264,10.0,3.0,CL
63,859,Placebo,17031,F,N,N,Y,Y,22.5,932,3.12,95,5396.0,244.90,133,165,11.6,3.0,D
295,877,D-penicillamine,12912,M,N,N,N,N,2.4,646,3.83,102,855.0,127.00,194,306,10.3,3.0,CL
144,943,Placebo,19098,F,N,Y,N,S,28.0,556,3.26,152,3896.0,198.40,171,335,10.0,3.0,D
402,943,NaN,18993,F,NaN,NaN,NaN,N,0.8,NaN,3.01,NaN,NaN,NaN,NaN,256,10.6,3.0,C
184,974,Placebo,13736,F,N,Y,N,N,11.0,674,3.55,358,2412.0,167.40,140,471,9.8,3.0,D
413,989,NaN,12784,F,NaN,NaN,NaN,N,0.7,NaN,3.23,NaN,NaN,NaN,NaN,312,10.8,3.0,C
416,1055,NaN,20819,F,NaN,NaN,NaN,N,1.6,NaN,3.42,NaN,NaN,NaN,NaN,143,9.9,3.0,C
409,1067,NaN,15706,F,NaN,NaN,NaN,N,0.7,NaN,3.73,NaN,NaN,NaN,NaN,214,10.8,3.0,C
410,1072,NaN,14245,F,NaN,NaN,NaN,N,1.5,NaN,3.81,NaN,NaN,NaN,NaN,255,10.8,3.0,C
215,1080,Placebo,15037,F,N,N,N,N,5.9,1276,3.85,141,1204.0,203.05,157,216,10.7,3.0,D
408,1086,NaN,18628,F,NaN,NaN,NaN,S,1.9,NaN,3.17,NaN,NaN,NaN,NaN,162,10.7,3.0,C
404,1092,NaN,14610,F,NaN,NaN,NaN,N,4.6,NaN,3.60,NaN,NaN,NaN,NaN,337,10.4,3.0,C
370,1095,NaN,18263,F,NaN,NaN,NaN,N,16.0,NaN,3.36,NaN,NaN,NaN,NaN,384,10.0,3.0,D
412,1097,NaN,24472,F,NaN,NaN,NaN,N,1.0,NaN,3.58,NaN,NaN,NaN,NaN,244,10.8,3.0,C
411,1119,NaN,18628,F,NaN,NaN,NaN,N,0.6,NaN,3.57,NaN,NaN,NaN,NaN,286,10.6,3.0,C
407,1129,NaN,19724,M,NaN,NaN,NaN,N,1.1,NaN,3.69,NaN,NaN,NaN,NaN,220,10.8,3.0,C
405,1150,NaN,18993,F,NaN,NaN,NaN,N,1.0,NaN,3.64,NaN,NaN,NaN,NaN,340,10.6,3.0,C
152,1152,D-penicillamine,25546,M,N,Y,N,N,2.3,586,3.01,243,2276.0,114.70,126,339,10.9,3.0,D
69,1170,D-penicillamine,18021,F,N,Y,Y,S,20.0,652,3.46,159,3292.0,215.45,184,227,12.4,3.0,D
169,1212,Placebo,12963,F,N,N,N,N,1.3,408,4.22,67,1387.0,142.60,137,295,10.1,3.0,D
305,1216,Placebo,15730,F,N,Y,Y,N,2.9,426,3.61,73,5184.0,288.00,144,275,10.6,3.0,C
304,1230,D-penicillamine,12979,F,N,N,N,N,0.5,219,3.93,22,663.0,45.00,75,246,10.8,3.0,C
326,1236,NaN,18993,F,NaN,NaN,NaN,N,1.5,NaN,3.42,NaN,NaN,NaN,NaN,246,10.3,3.0,C
299,1293,D-penicillamine,13913,F,N,N,N,N,2.4,342,3.76,90,1653.0,150.00,127,213,10.8,3.0,C
138,1297,D-penicillamine,18719,M,N,Y,N,N,7.3,426,3.93,262,2424.0,145.70,218,252,10.5,3.0,D
298,1300,Placebo,19258,F,N,Y,N,N,1.1,340,3.37,73,289.0,97.00,93,243,10.2,3.0,C
292,1329,Placebo,18352,M,N,Y,N,N,8.6,546,3.73,84,1070.0,127.00,153,291,11.2,3.0,C
375,1347,NaN,18993,F,NaN,NaN,NaN,N,1.7,NaN,3.24,NaN,NaN,NaN,NaN,231,10.5,3.0,CL
55,1360,D-penicillamine,24020,M,N,N,N,N,1.8,416,3.94,121,10165.0,79.98,219,213,11.0,3.0,D
290,1363,D-penicillamine,24101,F,N,N,N,N,1.4,294,3.57,33,722.0,93.00,69,283,9.8,3.0,C
392,1368,NaN,25202,F,NaN,NaN,NaN,N,0.4,NaN,3.03,NaN,NaN,NaN,NaN,173,10.9,3.0,C
286,1408,D-penicillamine,14191,F,N,Y,Y,N,2.0,310,3.36,70,1257.0,122.00,118,143,9.8,3.0,C
280,1412,D-penicillamine,16858,F,N,N,N,N,1.6,325,3.69,69,2583.0,142.00,140,284,9.6,3.0,C
130,1413,Placebo,16154,F,N,Y,Y,N,17.4,1775,3.43,205,2065.0,165.85,97,418,11.5,3.0,D
284,1418,Placebo,17738,F,N,N,N,N,1.3,291,3.44,75,1082.0,85.00,195,251,9.5,3.0,C
390,1419,NaN,24837,M,NaN,NaN,NaN,N,3.0,NaN,3.15,NaN,NaN,NaN,NaN,139,10.0,3.0,C
148,1427,Placebo,11273,F,N,Y,N,N,7.2,1015,3.26,247,3836.0,198.40,280,330,9.8,3.0,D
277,1434,Placebo,12816,F,N,N,N,S,1.0,317,3.56,44,1636.0,84.00,111,394,9.8,3.0,C
26,1444,Placebo,19002,F,N,Y,Y,N,5.2,1128,3.68,53,3228.0,165.85,166,421,9.9,3.0,D
376,1478,NaN,16071,M,NaN,NaN,NaN,N,9.5,NaN,3.63,NaN,NaN,NaN,NaN,292,10.2,3.0,D
64,1487,Placebo,22977,F,N,Y,N,N,2.1,373,3.50,52,1009.0,150.35,188,178,11.0,3.0,D
5,1504,Placebo,13918,F,N,Y,Y,N,3.4,279,3.53,143,671.0,113.15,72,136,10.9,3.0,CL
159,1536,Placebo,16714,M,N,N,N,N,2.5,317,3.46,217,714.0,130.20,140,207,10.1,3.0,D
264,1542,Placebo,16122,F,N,Y,Y,N,3.4,356,3.12,188,1911.0,92.00,130,318,11.2,3.0,CL
273,1558,Placebo,17320,F,N,N,Y,N,2.2,328,3.46,75,1677.0,87.00,116,202,9.6,3.0,C
270,1568,D-penicillamine,9598,F,N,Y,Y,N,1.0,448,3.74,102,1128.0,71.00,117,228,10.2,3.0,C
271,1569,Placebo,18435,F,N,Y,N,N,1.0,321,3.50,94,955.0,111.00,177,289,9.7,3.0,C
186,1576,D-penicillamine,25873,F,N,N,Y,S,2.0,225,3.53,51,933.0,69.75,62,200,12.7,3.0,D
199,1592,D-penicillamine,14872,F,N,N,N,N,2.1,392,3.43,52,1395.0,184.45,194,328,10.2,3.0,C
266,1614,D-penicillamine,20567,F,N,N,N,N,0.5,318,3.32,52,613.0,70.00,260,279,10.2,3.0,C
259,1615,Placebo,21904,F,N,Y,N,N,3.1,277,2.97,42,1110.0,125.00,126,221,9.8,3.0,C
385,1635,NaN,20089,F,NaN,NaN,NaN,N,0.7,NaN,2.93,NaN,NaN,NaN,NaN,209,10.6,3.0,C
387,1653,NaN,17897,F,NaN,NaN,NaN,S,13.6,NaN,3.00,NaN,NaN,NaN,NaN,233,9.9,3.0,C
386,1654,NaN,19724,M,NaN,NaN,NaN,N,1.7,NaN,2.38,NaN,NaN,NaN,NaN,166,9.8,3.0,C
86,1657,D-penicillamine,19270,F,N,Y,Y,N,5.0,1600,3.21,75,2656.0,82.15,174,181,10.9,3.0,D
262,1666,Placebo,15628,F,N,Y,N,N,2.8,322,3.06,65,2562.0,91.00,209,231,9.5,3.0,C
261,1677,Placebo,19126,F,N,Y,Y,N,3.2,375,3.14,129,857.0,89.00,NaNN,375,9.5,3.0,C
244,1690,D-penicillamine,16374,F,N,N,Y,N,3.9,350,3.22,121,1268.0,272.80,231,270,9.6,3.0,D
256,1701,D-penicillamine,11485,F,N,N,N,N,1.1,336,3.74,48,823.0,84.00,108,242,9.7,3.0,C
380,1725,NaN,12053,F,NaN,NaN,NaN,N,2.9,NaN,4.08,NaN,NaN,NaN,NaN,418,10.5,3.0,CL
255,1735,Placebo,12897,F,N,Y,Y,N,0.7,193,3.85,35,466.0,53.00,118,156,10.3,3.0,C
248,1785,Placebo,20241,F,N,Y,N,N,0.8,324,3.51,39,1237.0,66.65,146,371,10.0,3.0,C
214,1786,Placebo,25329,F,N,Y,N,N,0.9,404,3.43,34,1866.0,79.05,224,236,9.9,3.0,D
245,1790,Placebo,16718,F,N,Y,N,N,0.6,273,3.65,48,794.0,52.70,214,305,9.6,3.0,C
242,1810,D-penicillamine,23585,F,N,Y,N,N,1.9,354,2.97,86,1553.0,196.85,152,277,9.9,3.0,C
240,1831,D-penicillamine,20483,F,N,N,N,N,0.4,232,3.72,24,369.0,51.15,139,326,10.1,3.0,C
7,1832,Placebo,20284,F,N,Y,N,N,1.0,322,4.09,52,824.0,60.45,213,204,9.7,3.0,C
235,1882,Placebo,12120,F,N,Y,N,N,13.0,1336,4.16,71,3510.0,209.25,111,338,11.9,3.0,C
237,1882,D-penicillamine,21828,F,N,Y,N,N,1.6,442,2.95,105,820.0,85.25,108,181,10.1,3.0,C
236,1908,D-penicillamine,14019,F,N,Y,Y,N,1.5,253,3.79,67,1006.0,139.50,106,341,9.7,3.0,C
365,1925,NaN,23011,F,NaN,NaN,NaN,N,0.9,NaN,3.58,NaN,NaN,NaN,NaN,224,10.0,3.0,C
224,1945,D-penicillamine,14106,F,N,N,N,N,1.0,309,3.66,67,1214.0,158.10,101,309,9.7,3.0,C
232,1951,D-penicillamine,18329,F,N,Y,N,N,0.4,267,3.02,47,1001.0,133.30,87,265,10.6,3.0,C
228,1967,Placebo,13486,F,N,N,N,N,0.7,215,3.35,41,645.0,93.00,74,165,9.6,3.0,C
226,1978,Placebo,20708,F,N,Y,N,N,0.5,223,3.70,39,884.0,75.95,104,231,9.6,3.0,C
374,1980,NaN,18628,F,NaN,NaN,NaN,N,0.7,NaN,3.10,NaN,NaN,NaN,NaN,274,10.6,3.0,C
377,1987,NaN,12053,F,NaN,NaN,NaN,N,2.2,NaN,3.76,NaN,NaN,NaN,NaN,253,9.9,3.0,C
120,2033,D-penicillamine,12839,M,N,N,N,N,3.5,325,3.98,444,766.0,130.20,210,344,10.6,3.0,CL
163,2055,D-penicillamine,19540,F,N,N,N,N,0.3,233,4.08,20,622.0,66.65,68,358,9.9,3.0,D
205,2081,D-penicillamine,17889,F,Y,N,N,N,2.5,382,3.55,108,1516.0,238.70,NaNN,126,10.3,3.0,D
204,2090,Placebo,22857,F,N,N,N,N,0.7,255,3.74,23,1024.0,77.50,58,281,10.2,3.0,D
110,2105,D-penicillamine,14212,F,N,Y,Y,N,1.9,486,3.54,74,1052.0,108.50,109,141,10.9,3.0,D
219,2157,Placebo,15601,F,N,N,N,N,1.6,215,4.17,67,936.0,134.85,85,176,9.6,3.0,C
216,2168,D-penicillamine,21610,F,N,N,N,N,0.5,NaNN,3.68,20,856.0,55.80,NaNN,146,10.4,3.0,C
212,2176,Placebo,17263,F,N,N,N,N,1.2,232,3.98,11,1074.0,100.75,99,223,9.9,3.0,C
213,2178,D-penicillamine,18337,F,N,N,Y,N,0.5,400,3.40,9,1134.0,96.10,55,356,10.2,3.0,C
211,2195,Placebo,19327,F,N,N,N,N,1.3,NaNN,3.76,27,1282.0,100.75,NaNN,114,10.3,3.0,C
367,2202,NaN,23376,F,NaN,NaN,NaN,N,1.1,NaN,3.49,NaN,NaN,NaN,NaN,166,9.8,3.0,C
59,2224,D-penicillamine,14754,F,N,Y,Y,N,0.8,329,3.50,49,7622.8,126.42,124,321,10.6,3.0,D
363,2249,NaN,16071,F,NaN,NaN,NaN,N,0.6,NaN,3.50,NaN,NaN,NaN,NaN,150,9.9,3.0,C
46,2256,D-penicillamine,16728,F,N,Y,N,N,5.7,482,2.84,161,11552.0,136.74,165,518,12.7,3.0,D
118,2288,D-penicillamine,17844,F,N,Y,N,N,3.5,390,3.30,67,878.0,137.95,93,207,10.2,3.0,D
172,2301,Placebo,18215,F,N,N,Y,N,1.3,205,3.34,65,1031.0,91.45,126,217,9.8,3.0,C
200,2318,Placebo,11773,F,N,N,Y,N,4.7,236,3.55,112,1391.0,137.95,114,332,9.9,3.0,C
355,2338,NaN,14245,F,NaN,NaN,NaN,N,1.6,NaN,3.75,NaN,NaN,NaN,NaN,145,10.4,3.0,C
111,2350,D-penicillamine,15031,F,N,N,N,N,5.5,528,4.18,77,2404.0,172.05,78,467,10.7,3.0,CL
320,2403,NaN,16071,F,NaN,NaN,NaN,S,0.4,NaN,3.81,NaN,NaN,NaN,NaN,226,10.5,3.0,C
88,2452,Placebo,15119,F,N,N,N,S,0.6,296,4.06,37,1032.0,80.60,83,442,12.0,3.0,C
189,2456,Placebo,18499,F,N,Y,N,N,1.3,360,3.63,52,1812.0,97.65,164,256,9.9,3.0,C
8,2466,Placebo,19379,F,N,N,N,N,0.3,280,4.00,52,4651.2,28.38,189,373,11.0,3.0,D
6,2503,Placebo,24201,F,N,Y,N,N,0.8,248,3.98,50,944.0,93.00,63,NaNN,11.0,3.0,D
109,2504,Placebo,16094,F,N,N,N,N,0.5,120,3.61,53,804.0,110.05,52,271,10.6,3.0,C
185,2527,D-penicillamine,17664,F,N,N,N,N,0.8,256,3.54,42,1132.0,74.40,94,192,10.5,3.0,C
358,2537,NaN,23376,F,NaN,NaN,NaN,N,0.8,NaN,3.49,NaN,NaN,NaN,NaN,314,10.3,3.0,C
180,2563,Placebo,15548,F,N,N,N,N,4.7,478,4.38,44,1629.0,237.15,76,175,10.4,3.0,C
171,2574,D-penicillamine,19237,F,N,N,N,N,0.5,NaNN,4.52,31,784.0,74.40,NaNN,361,10.1,3.0,C
47,2576,Placebo,17323,F,N,N,N,N,0.5,316,3.65,68,1716.0,187.55,71,356,9.8,3.0,C
146,2615,Placebo,12369,F,N,N,N,S,1.2,NaNN,3.89,58,1284.0,173.60,NaNN,239,9.4,3.0,C
175,2624,Placebo,19049,F,N,N,N,N,0.8,283,3.80,152,718.0,108.50,168,340,10.1,3.0,C
170,2692,D-penicillamine,17774,F,N,N,N,N,1.2,390,3.61,32,1509.0,88.35,52,263,9.0,3.0,C
67,2769,Placebo,18733,F,N,N,N,N,1.1,466,3.91,84,1787.0,328.60,185,261,10.0,3.0,D
160,2772,Placebo,20955,F,N,N,N,N,0.6,217,3.62,13,414.0,75.95,119,224,10.5,3.0,C

¿Qué pasa si quiero el número de días en orden decreciente y la etapa en orden creciente?

In [60]:
cirrosis_orden_etapa_creciente_dias_decreciente = cirrosis.sort_values(by=['Stage', 'N_Days'], ascending=[True, False])
cirrosis_orden_etapa_creciente_dias_decreciente.head(5)

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
ID,,,,,,,,,,,,,,,,,,,
58,4459,D-penicillamine,16279,M,N,N,N,N,0.7,242,4.08,73,5890.0,56.76,118,NaNN,10.6,1.0,C
61,4256,Placebo,16034,M,N,N,N,N,0.6,216,3.94,28,601.0,60.45,188,211,13.0,1.0,C
73,4190,Placebo,14060,F,N,N,N,N,0.7,132,3.60,17,423.0,49.60,56,265,11.0,1.0,C
65,3992,D-penicillamine,14684,F,N,N,N,N,1.2,256,3.60,74,724.0,141.05,108,430,10.0,1.0,C
98,3823,D-penicillamine,10550,F,N,N,N,N,1.0,239,3.77,77,1877.0,97.65,101,312,10.2,1.0,C

¿Afecta el orden en el by? Sí, es la jerarquía dijera José...

In [64]:
cirrosis_orden_dias_decreciente_etapa_creciente = cirrosis.sort_values(by=['N_Days', 'Stage'], ascending=[False, True])
cirrosis_orden_dias_decreciente_etapa_creciente

,N_Days,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage,Status
ID,,,,,,,,,,,,,,,,,,,
325,4795,NaN,12419,F,NaN,NaN,NaN,N,1.8,NaN,3.24,NaN,NaN,NaN,NaN,NaN,18.0,2.0,C
43,4556,D-penicillamine,17850,F,N,N,N,N,1.1,361,3.64,36,5430.2,67.08,89,203,10.6,2.0,C
32,4523,Placebo,19722,F,N,Y,N,N,1.8,262,3.34,101,7277.0,82.56,158,286,10.6,4.0,C
29,4509,Placebo,23331,F,N,N,N,N,0.7,370,3.78,24,5833.0,73.53,86,390,10.6,2.0,C
2,4500,D-penicillamine,20617,F,N,Y,Y,N,1.1,302,4.14,54,7394.8,113.52,88,221,10.6,3.0,C
40,4467,D-penicillamine,17046,F,N,N,N,N,1.3,NaNN,3.34,105,11046.6,104.49,NaNN,358,11.0,4.0,C
58,4459,D-penicillamine,16279,M,N,N,N,N,0.7,242,4.08,73,5890.0,56.76,118,NaNN,10.6,1.0,C
42,4453,Placebo,12307,F,N,Y,Y,N,2.1,NaNN,3.54,122,8778.0,56.76,NaNN,344,11.0,4.0,C
48,4427,Placebo,17947,M,N,N,N,N,1.9,259,3.70,281,10396.8,188.34,178,214,11.0,3.0,C
60,4365,D-penicillamine,21324,F,N,N,N,N,0.9,604,3.40,82,876.0,71.30,58,228,10.3,3.0,C
61,4256,Placebo,16034,M,N,N,N,N,0.6,216,3.94,28,601.0,60.45,188,211,13.0,1.0,C
19,4232,D-penicillamine,18102,F,N,Y,N,S,0.7,235,3.56,39,1881.0,93.00,123,209,11.0,3.0,C
327,4214,NaN,17897,F,NaN,NaN,NaN,N,1.2,NaN,3.99,NaN,NaN,NaN,NaN,NaN,11.2,2.0,C
71,4196,Placebo,17841,F,N,Y,N,N,1.2,258,3.57,79,2201.0,120.90,76,410,11.5,4.0,C
66,4191,D-penicillamine,16967,M,N,Y,N,N,1.4,427,3.70,105,1909.0,182.90,171,123,11.0,3.0,D
73,4190,Placebo,14060,F,N,N,N,N,0.7,132,3.60,17,423.0,49.60,56,265,11.0,1.0,C
72,4184,Placebo,11868,F,N,N,N,N,0.5,320,3.54,51,1243.0,122.45,80,225,10.0,3.0,C
25,4127,Placebo,16463,F,N,N,N,N,0.7,298,4.10,40,661.0,106.95,66,324,11.3,2.0,C
24,4079,D-penicillamine,16261,M,N,Y,N,N,2.1,456,4.00,124,5719.0,221.88,230,70,9.9,2.0,D
313,4062,NaNN,21915,F,NaNN,NaNN,NaNN,N,0.7,NaN,3.65,NaN,NaN,NaN,NaN,378,11.0,NaN,C
83,4050,D-penicillamine,20459,F,N,Y,N,S,1.3,250,3.50,48,1138.0,71.30,100,81,12.9,4.0,C
68,4039,D-penicillamine,11912,F,N,N,N,N,0.7,174,4.09,58,642.0,71.30,46,203,10.6,3.0,C
84,4032,Placebo,20392,F,N,N,N,N,0.4,263,3.76,29,1345.0,137.95,74,181,11.2,3.0,C
45,4025,Placebo,15265,F,N,N,N,N,0.6,NaNN,3.93,19,1826.0,71.30,NaNN,474,10.9,2.0,C
65,3992,D-penicillamine,14684,F,N,N,N,N,1.2,256,3.60,74,724.0,141.05,108,430,10.0,1.0,C
34,3933,D-penicillamine,19015,F,N,N,N,N,0.8,364,3.70,37,1840.0,170.50,64,273,10.5,2.0,C
93,3913,D-penicillamine,13344,F,N,N,N,N,1.3,353,3.67,73,2039.0,232.50,68,380,11.1,2.0,C
51,3853,Placebo,19025,F,N,N,N,N,0.8,276,3.60,54,4332.0,99.33,143,273,10.6,2.0,D
96,3850,D-penicillamine,17841,F,N,N,N,N,1.0,NaNN,3.70,33,1258.0,99.20,NaNN,338,10.4,3.0,C
31,3839,Placebo,15177,F,N,Y,N,N,4.7,296,3.44,114,9933.2,206.40,101,195,10.3,2.0,D
98,3823,D-penicillamine,10550,F,N,N,N,N,1.0,239,3.77,77,1877.0,97.65,101,312,10.2,1.0,C
99,3820,Placebo,17703,M,N,N,N,N,1.8,460,3.35,148,1472.0,108.50,118,172,10.2,2.0,C
11,3762,Placebo,19619,F,N,Y,Y,N,1.4,259,4.16,46,1104.0,79.05,79,258,12.0,4.0,D
79,3707,D-penicillamine,16990,F,N,Y,N,N,0.8,315,4.24,13,1637.0,170.50,70,426,10.9,3.0,C
16,3672,Placebo,14772,F,N,N,N,N,0.7,204,3.66,28,685.0,72.85,58,198,10.8,3.0,C
36,3611,Placebo,20604,F,N,N,N,N,0.3,172,3.39,18,558.0,71.30,96,311,10.6,2.0,C
15,3584,D-penicillamine,23612,F,N,N,N,N,0.8,231,3.87,173,9009.8,127.71,96,295,11.0,3.0,D
101,3581,Placebo,16418,F,N,N,N,N,0.9,400,3.60,31,1689.0,164.30,166,327,10.4,3.0,C
13,3577,Placebo,16688,F,N,N,N,N,0.7,281,3.85,40,1181.0,88.35,130,244,10.6,3.0,C
82,3574,D-penicillamine,24585,F,N,N,N,N,4.5,472,4.09,154,1580.0,117.80,272,412,11.1,3.0,D
314,3561,NaN,23741,F,NaN,NaN,NaN,S,1.4,NaN,3.04,NaN,NaN,NaN,NaN,331,12.1,4.0,D
335,3527,NaN,20089,F,NaN,NaN,NaN,N,0.6,NaN,4.15,NaN,NaN,NaN,NaN,280,10.1,2.0,C
323,3523,NaN,14610,F,NaN,NaN,NaN,N,0.6,NaN,4.04,NaN,NaN,NaN,NaN,130,11.2,2.0,C
340,3495,NaN,19358,F,NaN,NaN,NaN,N,5.4,NaN,4.19,NaN,NaN,NaN,NaN,141,11.2,2.0,C
339,3492,NaN,21915,F,NaN,NaN,NaN,N,0.6,NaN,4.38,NaN,NaN,NaN,NaN,269,10.6,2.0,C
324,3468,NaN,23011,F,NaN,NaN,NaN,N,0.6,NaN,3.94,NaN,NaN,NaN,NaN,234,11.5,2.0,C
70,3458,D-penicillamine,20600,F,N,N,N,N,0.6,NaNN,4.64,20,666.0,54.25,NaNN,265,10.6,2.0,C
21,3445,Placebo,23445,M,N,Y,Y,N,0.6,252,3.83,41,843.0,65.10,83,336,11.4,4.0,C
112,3445,Placebo,20256,F,N,Y,Y,N,2.0,267,3.67,89,754.0,196.85,90,136,11.8,4.0,D
44,3428,Placebo,13727,F,N,Y,Y,Y,3.3,299,3.55,131,1029.0,119.35,50,199,11.7,3.0,D
115,3422,Placebo,15574,F,N,N,Y,N,0.7,303,4.19,81,1584.0,111.60,156,307,10.3,3.0,C
114,3395,Placebo,19295,M,N,N,N,N,3.2,259,4.30,208,1040.0,110.05,78,268,11.7,3.0,D
107,3388,Placebo,22836,F,N,N,N,N,0.6,212,4.03,10,648.0,71.30,77,316,17.1,1.0,C
85,3358,Placebo,17246,F,N,Y,N,N,2.1,262,3.48,58,2045.0,89.90,84,225,11.5,4.0,D
116,3336,D-penicillamine,22306,F,N,N,Y,S,3.0,458,3.63,74,1588.0,106.95,382,438,9.9,3.0,C
122,3297,D-penicillamine,20248,F,N,N,N,N,0.6,298,4.13,29,758.0,65.10,85,256,10.7,3.0,C
57,3282,D-penicillamine,19567,F,N,Y,N,S,2.3,260,3.18,231,11320.2,105.78,94,216,12.4,3.0,D
127,3255,Placebo,16109,F,N,N,N,N,0.5,268,4.08,9,1174.0,86.80,95,453,10.0,2.0,C
38,3244,Placebo,13378,F,N,Y,Y,N,3.3,383,3.53,102,1234.0,137.95,87,234,11.0,4.0,D
129,3239,D-penicillamine,23235,F,N,Y,N,N,0.9,420,3.87,30,1009.0,57.35,232,NaNN,9.7,3.0,C
342,3231,NaN,18263,F,NaN,NaN,NaN,N,0.9,NaN,4.01,NaN,NaN,NaN,NaN,244,10.5,3.0,C
106,3222,D-penicillamine,25023,F,Y,Y,N,N,2.1,NaNN,3.90,50,1087.0,103.85,NaNN,137,10.6,2.0,D
33,3170,Placebo,18731,F,N,N,N,N,0.8,210,3.19,82,1592.0,218.55,113,180,12.0,3.0,D
344,3157,NaN,13149,F,NaN,NaN,NaN,N,8.9,NaN,3.76,NaN,NaN,NaN,NaN,209,10.6,3.0,C
135,3150,D-penicillamine,15694,F,N,N,N,N,0.4,263,3.57,123,836.0,74.40,121,445,11.0,2.0,C
134,3149,Placebo,15463,F,N,N,N,N,0.7,578,3.67,35,1353.0,127.10,105,427,10.7,2.0,C
102,3099,D-penicillamine,20662,F,N,N,N,N,0.9,248,3.97,172,646.0,62.00,84,128,10.1,1.0,C
136,3098,D-penicillamine,20440,F,N,N,N,N,0.8,263,3.35,27,1636.0,116.25,69,206,9.8,2.0,C
105,3092,Placebo,12433,F,N,Y,N,N,1.1,464,4.20,38,1644.0,151.90,102,348,10.3,3.0,CL
62,3090,Placebo,22173,F,Y,N,N,N,1.3,302,2.75,58,1523.0,43.40,112,329,13.2,4.0,D
104,3086,D-penicillamine,15712,F,N,N,N,N,1.1,303,3.64,20,2108.0,128.65,53,349,11.1,2.0,D
124,3069,D-penicillamine,19318,M,N,Y,N,N,0.6,251,3.90,25,681.0,57.35,107,182,10.8,4.0,C
140,3059,D-penicillamine,19751,F,N,Y,N,N,1.1,290,4.09,38,2120.0,186.00,146,318,10.0,3.0,C
141,3050,D-penicillamine,17180,F,N,N,N,N,0.9,346,3.77,59,794.0,125.55,56,336,10.6,2.0,C
317,3030,NaN,22646,F,NaN,NaN,NaN,N,0.8,NaN,2.48,NaN,NaN,NaN,NaN,273,10.0,NaN,C
345,3021,NaN,17532,F,NaN,NaN,NaN,N,0.5,NaN,3.76,NaN,NaN,NaN,NaN,388,10.1,2.0,CL
147,2995,D-penicillamine,27398,F,N,N,N,S,1.2,288,3.37,32,791.0,57.35,114,213,10.7,2.0,C
137,2990,D-penicillamine,22960,F,N,N,N,N,1.1,399,3.60,79,3472.0,155.00,152,344,10.1,2.0,C
145,2976,Placebo,18701,F,N,N,Y,N,0.7,309,3.84,96,858.0,41.85,106,253,11.4,3.0,C
132,2944,D-penicillamine,14812,F,N,N,N,N,1.9,448,3.83,60,1052.0,127.10,175,181,9.8,3.0,C
150,2891,Placebo,12779,F,N,N,Y,N,1.0,NaNN,3.63,57,1536.0,134.85,NaNN,233,10.0,1.0,C
151,2870,D-penicillamine,20104,F,N,N,N,N,0.9,460,3.03,57,721.0,85.25,174,301,9.4,2.0,C
153,2863,D-penicillamine,18118,F,N,N,N,N,0.5,217,3.85,68,453.0,54.25,68,270,11.1,1.0,C
349,2855,NaN,19724,F,NaN,NaN,NaN,N,1.4,NaN,3.82,NaN,NaN,NaN,NaN,249,10.3,2.0,C
35,2847,Placebo,17758,F,N,N,N,N,1.2,314,3.20,201,12258.8,72.24,151,431,10.6,3.0,D
315,2844,NaN,19724,F,NaN,NaN,NaN,N,0.7,NaN,4.03,NaN,NaN,NaN,NaN,226,9.8,4.0,C
157,2835,Placebo,17809,F,N,N,N,N,0.6,286,3.42,34,1868.0,77.50,206,487,10.0,2.0,C
348,2834,NaN,18993,M,NaN,NaN,NaN,N,0.9,NaN,3.14,NaN,NaN,NaN,NaN,191,12.3,2.0,C
347,2812,NaN,18628,F,NaN,NaN,NaN,N,3.4,NaN,3.92,NaN,NaN,NaN,NaN,NaN,9.3,2.0,D
161,2797,Placebo,15612,F,N,N,N,N,2.3,502,3.56,4,964.0,120.90,180,269,9.6,2.0,C
133,2796,Placebo,22881,M,N,N,N,N,1.5,331,3.95,13,577.0,128.65,99,165,10.1,4.0,D
160,2772,Placebo,20955,F,N,N,N,N,0.6,217,3.62,13,414.0,75.95,119,224,10.5,3.0,C
67,2769,Placebo,18733,F,N,N,N,N,1.1,466,3.91,84,1787.0,328.60,185,261,10.0,3.0,D
166,2721,Placebo,15105,F,N,Y,N,N,5.7,1480,3.26,84,1960.0,457.25,108,213,9.5,2.0,C
352,2716,NaN,19358,F,NaN,NaN,NaN,N,0.6,NaN,4.19,NaN,NaN,NaN,NaN,330,9.9,1.0,C
168,2713,Placebo,17442,F,N,Y,N,N,0.4,257,3.80,44,842.0,97.65,110,NaNN,9.2,2.0,C
353,2698,NaN,22646,F,NaN,NaN,NaN,N,1.3,NaN,3.40,NaN,NaN,NaN,NaN,167,10.6,4.0,C
170,2692,D-penicillamine,17774,F,N,N,N,N,1.2,390,3.61,32,1509.0,88.35,52,263,9.0,3.0,C
90,2689,D-penicillamine,12227,M,N,N,N,N,1.6,660,4.22,94,1857.0,151.90,155,337,11.0,2.0,D
155,2666,Placebo,15909,F,N,Y,Y,S,0.6,220,3.35,57,1620.0,153.45,80,311,11.2,4.0,C
173,2657,D-penicillamine,11058,F,N,Y,Y,N,3.0,236,3.42,76,1403.0,89.90,86,493,9.8,2.0,C
174,2644,D-penicillamine,20296,F,N,N,N,N,0.5,NaNN,3.85,63,663.0,79.05,NaNN,311,9.7,1.0,C
336,2635,NaN,23741,F,NaN,NaN,NaN,N,2.1,NaN,3.34,NaN,NaN,NaN,NaN,155,10.1,4.0,C
175,2624,Placebo,19049,F,N,N,N,N,0.8,283,3.80,152,718.0,108.50,168,340,10.1,3.0,C
146,2615,Placebo,12369,F,N,N,N,S,1.2,NaNN,3.89,58,1284.0,173.60,NaNN,239,9.4,3.0,C
177,2609,Placebo,20254,F,N,N,N,N,0.9,258,4.01,49,559.0,43.40,133,277,10.4,2.0,C
50,2598,D-penicillamine,19544,F,N,Y,N,N,1.1,257,3.36,43,1080.0,106.95,73,128,10.6,4.0,D
108,2583,D-penicillamine,18393,F,N,N,N,N,0.4,127,3.50,14,1062.0,49.60,84,334,10.3,2.0,D
178,2580,D-penicillamine,25569,F,N,N,N,N,0.6,NaNN,4.08,51,665.0,74.40,NaNN,325,10.2,4.0,C
47,2576,Placebo,17323,F,N,N,N,N,0.5,316,3.65,68,1716.0,187.55,71,356,9.8,3.0,C
171,2574,D-penicillamine,19237,F,N,N,N,N,0.5,NaNN,4.52,31,784.0,74.40,NaNN,361,10.1,3.0,C
179,2573,Placebo,16050,F,N,Y,N,N,1.8,396,3.83,39,2148.0,102.30,133,278,9.9,4.0,C
180,2563,Placebo,15548,F,N,N,N,N,4.7,478,4.38,44,1629.0,237.15,76,175,10.4,3.0,C
357,2563,NaN,21185,F,NaN,NaN,NaN,N,3.0,NaN,3.46,NaN,NaN,NaN,NaN,109,10.4,4.0,C
181,2556,D-penicillamine,16279,F,N,Y,Y,N,1.4,248,3.58,63,554.0,75.95,106,79,10.3,4.0,C
182,2555,D-penicillamine,20799,F,N,Y,N,N,0.6,NaNN,3.69,161,674.0,26.35,NaNN,539,9.9,2.0,C
81,2540,D-penicillamine,23107,F,N,Y,Y,N,14.4,448,3.65,34,1218.0,60.45,318,385,11.7,4.0,D
358,2537,NaN,23376,F,NaN,NaN,NaN,N,0.8,NaN,3.49,NaN,NaN,NaN,NaN,314,10.3,3.0,C
359,2534,NaN,16802,F,NaN,NaN,NaN,N,0.8,NaN,2.89,NaN,NaN,NaN,NaN,419,NaN,1.0,C
185,2527,D-penicillamine,17664,F,N,N,N,N,0.8,256,3.54,42,1132.0,74.40,94,192,10.5,3.0,C
190,2504,D-penicillamine,19916,F,N,N,Y,N,2.3,NaNN,3.93,24,1828.0,133.30,NaNN,327,10.2,2.0,C
109,2504,Placebo,16094,F,N,N,N,N,0.5,120,3.61,53,804.0,110.05,52,271,10.6,3.0,C
6,2503,Placebo,24201,F,N,Y,N,N,0.8,248,3.98,50,944.0,93.00,63,NaNN,11.0,3.0,D
158,2475,D-penicillamine,13329,F,N,N,N,N,3.4,450,3.37,32,1408.0,116.25,118,313,11.2,2.0,CL
125,2468,Placebo,17233,F,N,Y,N,N,1.3,316,3.51,75,1162.0,147.25,137,238,10.0,4.0,CL
8,2466,Placebo,19379,F,N,N,N,N,0.3,280,4.00,52,4651.2,28.38,189,373,11.0,3.0,D
189,2456,Placebo,18499,F,N,Y,N,N,1.3,360,3.63,52,1812.0,97.65,164,256,9.9,3.0,C
88,2452,Placebo,15119,F,N,N,N,S,0.6,296,4.06,37,1032.0,80.60,83,442,12.0,3.0,C
194,2449,D-penicillamine,16216,F,N,N,N,N,1.5,293,4.30,50,975.0,125.55,56,336,9.1,2.0,C
192,2443,D-penicillamine,19256,F,N,Y,N,N,0.9,308,3.69,67,696.0,51.15,101,344,9.8,4.0,C
142,2419,Placebo,20354,F,N,Y,N,N,1.0,364,3.48,20,720.0,134.85,88,283,9.9,2.0,D
320,2403,NaN,16071,F,NaN,NaN,NaN,S,0.4,NaN,3.81,NaN,NaN,NaN,NaN,226,10.5,3.0,C
9,2400,D-penicillamine,15526,F,N,N,Y,N,3.2,562,3.08,79,2276.0,144.15,88,251,11.0,2.0,D
52,2386,D-penicillamine,18460,M,N,N,N,N,6.0,614,3.70,158,5084.4,206.40,93,362,10.6,1.0,D
197,2365,D-penicillamine,16300,F,N,N,N,N,0.6,266,3.97,25,1164.0,102.30,102,201,10.1,2.0,C
196,2363,D-penicillamine,20834,F,N,Y,Y,N,1.4,226,3.36,13,810.0,72.85,62,117,11.6,4.0,C
198,2357,Placebo,13075,F,N,N,Y,N,0.7,286,2.90,38,1692.0,141.05,90,381,9.6,2.0,C
111,2350,D-penicillamine,15031,F,N,N,N,N,5.5,528,4.18,77,2404.0,172.05,78,467,10.7,3.0,CL
355,2338,NaN,14245,F,NaN,NaN,NaN,N,1.6,NaN,3.75,NaN,NaN,NaN,NaN,145,10.4,3.0,C
188,2332,D-penicillamine,22873,F,N,Y,N,N,0.7,187,3.48,41,654.0,120.90,98,164,11.0,4.0,C
195,2330,D-penicillamine,10795,F,N,Y,N,N,3.7,347,3.90,76,2544.0,221.65,90,129,11.5,4.0,C
200,2318,Placebo,11773,F,N,N,Y,N,4.7,236,3.55,112,1391.0,137.95,114,332,9.9,3.0,C
172,2301,Placebo,18215,F,N,N,Y,N,1.3,205,3.34,65,1031.0,91.45,126,217,9.8,3.0,C
39,2297,D-penicillamine,20232,F,N,Y,N,N,0.7,282,3.00,52,9066.8,72.24,111,563,10.6,4.0,D
201,2294,Placebo,15009,F,N,Y,N,N,0.6,235,3.20,26,1758.0,106.95,67,228,10.8,4.0,C
118,2288,D-penicillamine,17844,F,N,Y,N,N,3.5,390,3.30,67,878.0,137.95,93,207,10.2,3.0,D
337,2286,NaN,20454,F,NaN,NaN,NaN,N,1.8,NaN,3.64,NaN,NaN,NaN,NaN,141,10.0,NaN,D
202,2272,D-penicillamine,22514,F,N,N,N,N,0.5,223,3.80,15,1044.0,80.60,89,514,10.0,2.0,C
362,2267,NaN,17897,F,NaN,NaN,NaN,N,18.0,NaN,3.04,NaN,NaN,NaN,NaN,432,9.7,2.0,CL
46,2256,D-penicillamine,16728,F,N,Y,N,N,5.7,482,2.84,161,11552.0,136.74,165,518,12.7,3.0,D
206,2255,D-penicillamine,22642,F,N,N,N,N,0.6,213,4.07,12,5300.0,57.35,68,240,11.0,1.0,C
363,2249,NaN,16071,F,NaN,NaN,NaN,N,0.6,NaN,3.50,NaN,NaN,NaN,NaN,150,9.9,3.0,C
183,2241,Placebo,14705,F,N,N,N,N,0.5,201,3.73,44,1345.0,54.25,145,445,10.1,2.0,CL
210,2224,Placebo,18176,M,N,Y,N,N,0.9,346,3.37,81,1098.0,122.45,90,298,10.0,2.0,C
59,2224,D-penicillamine,14754,F,N,Y,Y,N,0.8,329,3.50,49,7622.8,126.42,124,321,10.6,3.0,D
203,2221,Placebo,13535,F,N,Y,N,N,0.5,149,4.04,227,598.0,52.70,57,166,9.9,2.0,C
209,2216,Placebo,19221,F,N,Y,Y,N,0.7,252,4.01,11,1210.0,72.85,58,309,9.5,2.0,C
367,2202,NaN,23376,F,NaN,NaN,NaN,N,1.1,NaN,3.49,NaN,NaN,NaN,NaN,166,9.8,3.0,C
211,2195,Placebo,19327,F,N,N,N,N,1.3,NaNN,3.76,27,1282.0,100.75,NaNN,114,10.3,3.0,C
213,2178,D-penicillamine,18337,F,N,N,Y,N,0.5,400,3.40,9,1134.0,96.10,55,356,10.2,3.0,C
212,2176,Placebo,17263,F,N,N,N,N,1.2,232,3.98,11,1074.0,100.75,99,223,9.9,3.0,C
207,2171,D-penicillamine,26580,F,N,N,N,S,0.6,NaNN,3.33,14,733.0,85.25,NaNN,259,10.1,4.0,C
218,2170,D-penicillamine,12636,F,N,N,N,N,0.5,NaNN,3.89,29,897.0,66.65,NaNN,423,10.1,1.0,C
216,2168,D-penicillamine,21610,F,N,N,N,N,0.5,NaNN,3.68,20,856.0,55.80,NaNN,146,10.4,3.0,C
219,2157,Placebo,15601,F,N,N,N,N,1.6,215,4.17,67,936.0,134.85,85,176,9.6,3.0,C
372,2149,NaN,13514,F,NaN,NaN,NaN,N,0.6,NaN,3.55,NaN,NaN,NaN,NaN,248,10.3,2.0,C
328,2111,NaN,19724,F,NaN,NaN,NaN,N,1.0,NaN,3.60,NaN,NaN,NaN,NaN,NaN,12.1,2.0,D
139,2106,Placebo,17080,F,N,Y,N,N,1.1,328,3.31,159,1260.0,94.55,134,142,11.6,4.0,C
110,2105,D-penicillamine,14212,F,N,Y,Y,N,1.9,486,3.54,74,1052.0,108.50,109,141,10.9,3.0,D
373,2103,NaN,22646,F,NaN,NaN,NaN,N,0.7,NaN,3.29,NaN,NaN,NaN,NaN,190,9.8,2.0,C
204,2090,Placebo,22857,F,N,N,N,N,0.7,255,3.74,23,1024.0,77.50,58,281,10.2,3.0,D
205,2081,D-penicillamine,17889,F,Y,N,N,N,2.5,382,3.55,108,1516.0,238.70,NaNN,126,10.3,3.0,D
316,2071,NaN,27394,F,NaN,NaN,NaN,S,0.7,NaN,3.96,NaN,NaN,NaN,NaN,NaN,11.3,4.0,D
163,2055,D-penicillamine,19540,F,N,N,N,N,0.3,233,4.08,20,622.0,66.65,68,358,9.9,3.0,D
221,2050,Placebo,20684,F,N,Y,N,N,0.9,360,3.65,72,3186.0,94.55,154,269,9.7,4.0,C
120,2033,D-penicillamine,12839,M,N,N,N,N,3.5,325,3.98,444,766.0,130.20,210,344,10.6,3.0,CL
225,2022,D-penicillamine,14161,F,N,N,N,N,0.7,274,3.66,108,1065.0,88.35,135,251,10.1,2.0,C
322,2011,NaN,23376,F,NaN,NaN,NaN,N,1.1,NaN,3.69,NaN,NaN,NaN,NaN,139,10.5,NaN,D
377,1987,NaN,12053,F,NaN,NaN,NaN,N,2.2,NaN,3.76,NaN,NaN,NaN,NaN,253,9.9,3.0,C
374,1980,NaN,18628,F,NaN,NaN,NaN,N,0.7,NaN,3.10,NaN,NaN,NaN,NaN,274,10.6,3.0,C
230,1979,Placebo,12641,F,N,Y,Y,N,3.3,302,3.41,51,310.0,83.70,44,95,11.5,4.0,C
226,1978,Placebo,20708,F,N,Y,N,N,0.5,223,3.70,39,884.0,75.95,104,231,9.6,3.0,C
228,1967,Placebo,13486,F,N,N,N,N,0.7,215,3.35,41,645.0,93.00,74,165,9.6,3.0,C
232,1951,D-penicillamine,18329,F,N,Y,N,N,0.4,267,3.02,47,1001.0,133.30,87,265,10.6,3.0,C
224,1945,D-penicillamine,14106,F,N,N,N,N,1.0,309,3.66,67,1214.0,158.10,101,309,9.7,3.0,C
233,1932,D-penicillamine,15591,F,N,Y,Y,N,0.9,514,3.06,412,2622.0,105.40,87,284,9.8,4.0,C
365,1925,NaN,23011,F,NaN,NaN,NaN,N,0.9,NaN,3.58,NaN,NaN,NaN,NaN,224,10.0,3.0,C
4,1925,D-penicillamine,19994,F,N,Y,Y,S,1.8,244,2.54,64,6121.8,60.63,92,183,10.3,4.0,D
236,1908,D-penicillamine,14019,F,N,Y,Y,N,1.5,253,3.79,67,1006.0,139.50,106,341,9.7,3.0,C
381,1899,NaN,14975,M,NaN,NaN,NaN,N,1.7,NaN,3.66,NaN,NaN,NaN,NaN,92,11.0,4.0,C
235,1882,Placebo,12120,F,N,Y,N,N,13.0,1336,4.16,71,3510.0,209.25,111,338,11.9,3.0,C
237,1882,D-penicillamine,21828,F,N,Y,N,N,1.6,442,2.95,105,820.0,85.25,108,181,10.1,3.0,C
238,1874,Placebo,24257,F,N,N,N,S,0.6,280,3.35,NaNN,1093.0,128.65,81,295,9.8,2.0,C
56,1847,Placebo,12279,F,N,Y,Y,N,1.1,498,3.80,88,13862.4,95.46,319,365,10.6,2.0,D
7,1832,Placebo,20284,F,N,Y,N,N,1.0,322,4.09,52,824.0,60.45,213,204,9.7,3.0,C
240,1831,D-penicillamine,20483,F,N,N,N,N,0.4,232,3.72,24,369.0,51.15,139,326,10.1,3.0,C
74,1827,D-penicillamine,18964,F,N,Y,Y,N,8.4,558,3.99,280,967.0,89.90,309,278,11.0,4.0,D
242,1810,D-penicillamine,23585,F,N,Y,N,N,1.9,354,2.97,86,1553.0,196.85,152,277,9.9,3.0,C
245,1790,Placebo,16718,F,N,Y,N,N,0.6,273,3.65,48,794.0,52.70,214,305,9.6,3.0,C
214,1786,Placebo,25329,F,N,Y,N,N,0.9,404,3.43,34,1866.0,79.05,224,236,9.9,3.0,D
248,1785,Placebo,20241,F,N,Y,N,N,0.8,324,3.51,39,1237.0,66.65,146,371,10.0,3.0,C
249,1783,D-penicillamine,17525,F,N,N,Y,N,1.3,242,3.20,35,1556.0,175.15,71,195,10.6,4.0,C
234,1776,Placebo,12557,F,N,N,N,N,0.9,578,3.35,78,976.0,116.25,177,322,11.2,2.0,C
252,1770,D-penicillamine,25006,F,N,Y,Y,N,1.1,246,3.35,116,924.0,113.15,90,317,10.0,4.0,C
250,1769,Placebo,14899,F,N,Y,N,N,0.6,299,3.36,23,2769.0,220.10,85,303,10.9,4.0,C
253,1765,D-penicillamine,28650,M,Y,Y,Y,N,7.1,243,3.03,380,983.0,158.10,154,97,11.2,4.0,C
330,1746,NaN,19724,M,NaN,NaN,NaN,N,3.5,NaN,3.63,NaN,NaN,NaN,NaN,325,10.3,2.0,D
89,1741,D-penicillamine,19155,F,N,Y,N,N,2.0,408,3.65,50,1083.0,110.05,98,200,11.4,2.0,D
255,1735,Placebo,12897,F,N,Y,Y,N,0.7,193,3.85,35,466.0,53.00,118,156,10.3,3.0,C
380,1725,NaN,12053,F,NaN,NaN,NaN,N,2.9,NaN,4.08,NaN,NaN,NaN,NaN,418,10.5,3.0,CL
258,1702,D-penicillamine,18806,F,N,N,N,N,1.1,414,3.44,80,1003.0,99.00,55,271,9.6,1.0,C
256,1701,D-penicillamine,11485,F,N,N,N,N,1.1,336,3.74,48,823.0,84.00,108,242,9.7,3.0,C
244,1690,D-penicillamine,16374,F,N,N,Y,N,3.9,350,3.22,121,1268.0,272.80,231,270,9.6,3.0,D
78,1690,D-penicillamine,17512,F,N,Y,N,N,6.3,436,3.02,75,2176.0,170.50,104,236,10.6,4.0,D
167,1682,D-penicillamine,22265,M,N,Y,N,N,0.9,376,3.86,200,1015.0,83.70,154,238,10.3,4.0,D
318,1680,NaN,15706,F,NaN,NaN,NaN,N,0.7,NaN,3.68,NaN,NaN,NaN,NaN,306,9.5,2.0,C
261,1677,Placebo,19126,F,N,Y,Y,N,3.2,375,3.14,129,857.0,89.00,NaNN,375,9.5,3.0,C
262,1666,Placebo,15628,F,N,Y,N,N,2.8,322,3.06,65,2562.0,91.00,209,231,9.5,3.0,C
86,1657,D-penicillamine,19270,F,N,Y,Y,N,5.0,1600,3.21,75,2656.0,82.15,174,181,10.9,3.0,D
260,1656,Placebo,27220,M,N,Y,N,N,5.6,232,3.59,188,1120.0,98.00,128,248,10.9,4.0,C
386,1654,NaN,19724,M,NaN,NaN,NaN,N,1.7,NaN,2.38,NaN,NaN,NaN,NaN,166,9.8,3.0,C
387,1653,NaN,17897,F,NaN,NaN,NaN,S,13.6,NaN,3.00,NaN,NaN,NaN,NaN,233,9.9,3.0,C
384,1639,NaN,21550,F,NaN,NaN,NaN,N,1.3,NaN,3.40,NaN,NaN,NaN,NaN,243,9.7,1.0,C
385,1635,NaN,20089,F,NaN,NaN,NaN,N,0.7,NaN,2.93,NaN,NaN,NaN,NaN,209,10.6,3.0,C
356,1616,NaN,24472,F,NaN,NaN,NaN,S,2.2,NaN,3.26,NaN,NaN,NaN,NaN,171,11.1,4.0,D
259,1615,Placebo,21904,F,N,Y,N,N,3.1,277,2.97,42,1110.0,125.00,126,221,9.8,3.0,C
257,1614,D-penicillamine,21281,F,N,N,N,N,0.5,280,4.23,36,377.0,56.00,146,227,10.6,2.0,C
266,1614,D-penicillamine,20567,F,N,N,N,N,0.5,318,3.32,52,613.0,70.00,260,279,10.2,3.0,C
199,1592,D-penicillamine,14872,F,N,N,N,N,2.1,392,3.43,52,1395.0,184.45,194,328,10.2,3.0,C
389,1581,NaN,24472,F,NaN,NaN,NaN,N,0.7,NaN,3.06,NaN,NaN,NaN,NaN,165,10.0,4.0,C
186,1576,D-penicillamine,25873,F,N,N,Y,S,2.0,225,3.53,51,933.0,69.75,62,200,12.7,3.0,D
271,1569,Placebo,18435,F,N,Y,N,N,1.0,321,3.50,94,955.0,111.00,177,289,9.7,3.0,C
270,1568,D-penicillamine,9598,F,N,Y,Y,N,1.0,448,3.74,102,1128.0,71.00,117,228,10.2,3.0,C
388,1560,NaN,14610,F,NaN,NaN,NaN,N,0.9,NaN,3.50,NaN,NaN,NaN,NaN,117,10.9,4.0,C
273,1558,Placebo,17320,F,N,N,Y,N,2.2,328,3.46,75,1677.0,87.00,116,202,9.6,3.0,C
264,1542,Placebo,16122,F,N,Y,Y,N,3.4,356,3.12,188,1911.0,92.00,130,318,11.2,3.0,CL
159,1536,Placebo,16714,M,N,N,N,N,2.5,317,3.46,217,714.0,130.20,140,207,10.1,3.0,D